task:
  name: FreeBSD $FREEBSD_VERSION ($TOOLCHAIN)

  freebsd_instance:
    cpu: 1
    image_family: $FREEBSD_IMAGE

  matrix:
    - env:
        FREEBSD_VERSION: 12.2
        FREEBSD_IMAGE: freebsd-12-2
    - env:
        FREEBSD_VERSION: 12.2 STABLE
        FREEBSD_IMAGE: freebsd-12-2-snap
    # - env:
    #     FREEBSD_VERSION: 13.0
    #     FREEBSD_IMAGE: freebsd-13-0-snap

  matrix:
    - env:
        TOOLCHAIN: stable
    - env:
        TOOLCHAIN: beta
    - env:
        TOOLCHAIN: nightly

  allow_failures: $TOOLCHAIN == 'nightly'

  env:
    CODECOV_TOKEN: ENCRYPTED[0535c7ad05b80db6bf8f60b0c14e94df3ca863405e40eb71458633cf05e502999cf4ea51effb7268ad49158a077e1a16]

  install_script:
    - pkg install -y npm jq curl kcov bash
    - curl -sSf https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile default --default-toolchain $TOOLCHAIN
  build_script:
    - . $HOME/.cargo/env
    - cargo build
  test_script:
    - . $HOME/.cargo/env
    - cargo test
    - |
      mkdir -p coverage-build
      for f in target/debug/deps/*; do
        if [ -x "$f" ]; then
          kcov --exclude-pattern=/.cargo,/.rustup,/usr/lib --include-path=$(pwd) --verify coverage-build/ "$f"
          rm -f "coverage-build/${f##*/}"
        fi
      done
  coverage_collect_upload_script:
    - kcov --merge coverage-merged/ coverage-build/
    - curl -sSfL "$(curl -sSf 'https://api.github.com/repos/codecov/uploader/releases/latest' | jq -r '.tarball_url')" -o codecov-uploader.tar.gz
    - tar -xzf codecov-uploader.tar.gz
    - mv codecov-uploader-*/ codecov-uploader/
    - (cd codecov-uploader && npm install && npm run build)
    - node codecov-uploader/dist/bin/codecov -e OS,TOOLCHAIN -n "$FREEBSD_IMAGE-$TOOLCHAIN" -Z -f coverage-merged/kcov-merged/cobertura.xml
